# PRIOR
#
# To create prior fluxes (no transport modeling).

inherit = base.ini

[experiment]
name = prior

[run]
chem_flux = true

[tracers]
num_tracers = 40

[chem_flux]
use_parameters_bio = true
parameters_file_bio = data/parameters_inversion.nc
